### ISSUE TITLE
Extension icons disappear from v0.0.25 to v0.0.30 or v0.0.31

### ISSUE THREAD

**Issue by Pierrotdx** [zoctarine/vscode-fiction-writer#16]
**Describe the bug**
The extension icons of left-side toolbar (picture below) and status bar disappear when passing from v0.0.25 to v0.0.30 or v0.0.31.

**To Reproduce**
1. Upgrade from v0.0.25 to v0.0.30 or v0.0.31.

**Expected behavior**
Being able to access the extension features from the left-side and status bar icons.

**Screenshots**
![Issue](https://user-images.githubusercontent.com/54754067/109429160-a4498a80-79fa-11eb-9576-907f2c031e18.jpg)

**Desktop**
 - OS: Windows

**Additional context**
Being a noob in VSCode extensions, I don't really know what kind of information is useful to debug, so let me know if anything is needed.

**Comment by zoctarine** [comment]
Thank you.
I am trying to fix the issue now. Will make a new release soon.

**Comment by zoctarine** [comment]
Version `0.0.33` released. 

It was an issue with including the `js-yaml` package.  And, also, a file rename done on windows was not case-sensitive.

I tested on both Linux and Windows now, and the extension loads normally.

Please let me know if it works for you.

Thank you.

**Comment by Pierrotdx** [comment]
It works fine now, thanks!
Great extension btw!
