### ISSUE TITLE
Replace all "--" with "—" in dialogueAutoCorrect

### ISSUE THREAD

**Issue by tojamrok** [zoctarine/vscode-fiction-writer#32]
Currently "--" characters are replaced by the "—" character when they occur at the beginning of the text line.  It would be good if all consecutive occurrences of "--" were replaced as well, so that following text:

-- Hi -- he said. -- I'm looking at you.

should be auto modified into:

— Hi — he said. — I'm looking at you.

**Comment by zoctarine** [comment]
In some languages, the dialogue marker should be em-dash `—` and it is used only at the beginning of a sentence. All other markers are en-dash character, that is a bit smaller `–`. 

I thing the best way to address this is to provide an additional option, that handles replacements of inner `--` characters to either em-dash or en-dash.

**Comment by zoctarine** [comment]
An options is added to handle beginning of line and rest of the line replacements
