### ISSUE TITLE
consider adding compile: false option to yaml

### ISSUE THREAD

**Issue by grahampcharles** [zoctarine/vscode-fiction-writer#36]
I like to keep scratch files (notes, outlines) together with my manuscript; these are usually `.md` files themselves, like `chapter-02-outline.md`. 

I would love a metadata tag that would prevent them from appearing in the final compile, like `compile: false` or something similar. 

Obviously, I can keep those scratch files somewhere else, but it's convenient to keep them adjacent to the manuscripts. I can also surround the entire file content with `<!-- -->` to prevent anything from being emitted, but then I lose vscode features.

**Comment by zoctarine** [comment]
Thank you for this suggestion. I will add in the next release. I am preparing the beta, with restructured options.
`compile: false` is good suggestion.

**Comment by grahampcharles** [comment]
> There will be also md support in notes files.

Oh, that's a good idea. Are you thinking that any suffix to a file name would be valid, then? like:

```
chapter-01.md        # the content file
chapter-01.md.txt    # a notes file
chapter-01.md.md     # a different notes file
chapter-01.md.outline.md     # my personal outline
chapter-01.md.other.md       # random stuff I want to keep track of...
...
```

If so, how will you select which file is displayed in the sidebar? Only `.md.txt` or `.md.md`, I assume?

**Comment by zoctarine** [comment]
One idea. If you have so many files, that you do not want do include in our final compiled document, would it be an idea to keep a `toc.md` file, as described here [TOC Document](https://zoctarine.github.io/vscode-fiction-writer/export/#the-toc-document).

Then you can include (by filename or by metadata `id` only the chapter files. You will be free to use any other naming conventions :) .

As for .md support in notes, i was thinking that .md will be leading, and .txt will be like a fallback. But I am still working on it.
