### ISSUE TITLE
allow dotx template files

### ISSUE THREAD

**Issue by grahampcharles** [zoctarine/vscode-fiction-writer#37]
**Is your feature request related to a problem? Please describe.**

When a Word template file (with a `dotx` extension) is set as the `markdown-fiction-writer.export.outputTemplate.file`, it doesn't work; a `docx` file must be selected. 

**Describe the solution you'd like**

I would love to be able to use a `dotx` template.

**Describe alternatives you've considered**

It works okay to use a `docx` file as a template, but is an extra step for me when I'm making template updates. (Update template, save off a dummy `template.docx` file.) 

**Additional context**

`dotx` seems like the right format for templates, but maybe they don't play well with pandoc (I bet that's it?) So this is pretty minor.

**Comment by grahampcharles** [comment]
Looking into this, I think it's likely you're just using the template file to feed to pandoc's `--reference-doc` option -- so there's no way to change the behavior unless pandoc does. Oh, well!

**Comment by zoctarine** [comment]
Yes, you are right. The template thing completely depends on pandoc. It gets a while to get the `docx` or `odt` right, but after that it works fine. They don't support `dotx` :)
