### ISSUE TITLE
make file inclusion recursive

### ISSUE THREAD

**Issue by grahampcharles** [zoctarine/vscode-fiction-writer#38]
Currently, if you include a file that itself contains included files, only the top-level includes are processed. Included files in the child files are simply rendered as the `{file name}` (or `{id}`).

I think that any included file should also have sub-includes parsed.

Obviously, this would require a mechanism to protect against looping (a includes b which includes a), but I still think it would be valuable.

**Comment by zoctarine** [comment]
Ah, it should work as you described. It also has a loop protection, that it does not include a file if it was already included. The fact that it does not work, means there is a bug somewhere.

Thanks for reporting it. I will start fixing it.
